# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a862d88ef26d0bf4844ad4501b9846d9bcc34e7b398558cd102e7a7e9ec48f8d760cc556e40f0db0ac82175018f59b197bb8f433cd64308ac902b6d8c12bab13

test:
  secret_key_base: c9f2968937ac03f34322a68c9bbd8a722f4a91993226cc81e753437cc6dea8ae6cecde0d866d670b6d527970e327ef039c834dc437056b9014daf043782c3e4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
